### ISSUE TITLE
Zerofox repo for integration

### ISSUE THREAD

**Issue by DNRRomero** [splunk-soar-connectors/.github#101]
**Name of the app**
zerofoxconnectors

**Integration**
ZeroFox Cyber Threat Intelligence Feeds

**About**
Allows for retrieving information from ZeroFox's Cyber Threat Intelligence Feeds
Thank you for contributing to Splunk SOAR!

**Comment by mpan-splunk** [comment]
Repo is created at: https://github.com/splunk-soar-connectors/zerofoxconnectors
