### ISSUE TITLE
include zerofoxalerts app

### ISSUE THREAD

**Issue by DNRRomero** [splunk-soar-connectors/.github#103]
**Name of the app**
zerofoxalerts

**Integration**
Allows for retrieving and performing actions on zerofox alerts

**About**
Allows for polling alerts to be mapped into splunk objects, as well as triggering simple actions such as modifying tags con alerts on the zerofox Api

**Comment by tonyc-phantom** [comment]
New repo created: https://github.com/splunk-soar-connectors/zerofoxalerts
