### ISSUE TITLE
TeamDynamix

### ISSUE THREAD

**Issue by ricardom-splunk** [splunk-soar-connectors/.github#104]
**Name of the app**
teamdynamix

**Integration**
TeamDynamix Web API

**About**
SOAR connector for TeamDynamix Web API

The initial version of the app leverages the authentication methods and endpoints described on the official docs:
https://solutions.teamdynamix.com/TDWebApi/

At a minimum, it will have the following actions:
- create ticket
- updated ticket
- delete ticket

Thank you for contributing to Splunk SOAR!

**Comment by tonyc-phantom** [comment]
New repo created: https://github.com/splunk-soar-connectors/teamdynamix
