### ISSUE TITLE
Spur Context

### ISSUE THREAD

**Issue by import-au** [splunk-soar-connectors/.github#105]
**Name of the app**
spur_context

**Integration**
Spur Context API
https://docs.spur.us/context-api?id=context-api

**About**
The Spur Context API provides REST API access for IP Context data. Visit our [website](https://spur.us/products/context-api) for more information on use-cases, integrations, and client successes

Thank you for contributing to Splunk SOAR!

**Comment by tonyc-phantom** [comment]
New repo created: https://github.com/splunk-soar-connectors/spur_context
