### ISSUE TITLE
New App Repository Request - googlecloudcompute

### ISSUE THREAD

**Issue by manasmbellani** [splunk-soar-connectors/.github#108]
**Name of the app**
googlecloudcompute

**Integration**
Google Cloud Compute Engine Service

**About**
This application will integration with Google Cloud's Compute Engine REST API service to perform various actions such as listing compute instances.

The initial set of actions for this app will be:
- test_connectivity
- list_vm_instances

Thank you for contributing to Splunk SOAR!

**Comment by tonyc-phantom** [comment]
The repo https://github.com/splunk-soar-connectors/googlecloudcompute has been created.
