### ISSUE TITLE
vectrandr

### ISSUE THREAD

**Issue by crestdatasystems** [splunk-soar-connectors/.github#109]
**Name of the app**
vectrandr

**Integration**
splunksoar

**About**
Vectra AI is the leader in AI-driven threat detection and response for hybrid and multi-cloud enterprises. Organizations worldwide rely on Vectra to stay ahead of modern cyber-attacks. The Vectra AI App enables the security operations team to consume Vectra's Quadrant User Experience signal and take appropriate action whether automated, semi-automated, or manual, using Splunk SOAR

Thank you for contributing to Splunk SOAR!

**Comment by crestdatasystems** [comment]
Hello @tonyc-phantom | @gary-phantom | @mpan-splunk | @ricardo-phantom 
Could you please approve and create vectrandr repo?

**Comment by ishans-crest** [comment]
Hello @crestdatasystems Please find the repo for vectrandr https://github.com/splunk-soar-connectors/vectrandr
