### ISSUE TITLE
New App - freshservice

### ISSUE THREAD

**Issue by dan3hr** [splunk-soar-connectors/.github#110]
freshservice
The name of app your are contributing. Please ensure the app name
follows our [naming convention](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONVENTIONS.md).

**Integration**
The technology that your app integrates with.
This app is to integrate with Fresh Service, an ITSM/ticketing tool, over their APIs.

**About**
Description of what the app does.
Actions:
- create ticket - Create a ticket (issue)
- get ticket - Get ticket (issue) information
- update ticket - Update ticket (issue)
- add note - Add a note to a ticket.
Thank you for contributing to Splunk SOAR!

**Comment by ishans-crest** [comment]
Repo has been created https://github.com/splunk-soar-connectors/freshservice
