### ISSUE TITLE
New app repository - Varonis SaaS

### ISSUE THREAD

**Issue by vkorenkov-varonis** [splunk-soar-connectors/.github#111]
**varonissaas**

**Integration**
Varonis SaaS

**About**
This pack enables you to streamline alerts and related forensic information from Varonis SaaS.

What does this app do?

- Enables retrieving alerts and manage alert status.
- Enables retrieving information related to alerts for investigation and threat hunting.
![image](https://github.com/splunk-soar-connectors/.github/assets/99330808/5b312e93-5867-4412-88d7-69967acf7799)

**Comment by tonyc-phantom** [comment]
The repo https://github.com/splunk-soar-connectors/varonissaas has been created.
