### ISSUE TITLE
Contributing to SOAR with our application for TrackMe

### ISSUE THREAD

**Issue by guilhemmarchand** [splunk-soar-connectors/.github#119]
**trackme**

Hi,

We would like to propose our freshly made Trackme App on SOAR, as the SOAR connector to interract with TrackMe for Splunk Enterprise & Splunk Cloud.

**Our application can be found in our own Git repo:**
- https://github.com/trackme-limited/trackme-app-on-soar

**And briefly documented here:**
- https://docs.trackme-solutions.com/latest/admin_guide_trackme_app_on_soar.html

The TrackMe App on SOAR therefore intreracts with TrackMe for Splunk Enterprise & Splunk Cloud, allowing to automate TrackMe tasks such as retrieving the status of TrackMe entities, updating key behaviours of entities, or interact with advanced TrackMe features such as its Machine Learning features.

TrackMe for Splunk provides visibility and operational excellence to monitor at scale your Splunk data sources availability & quality, scheduled Splunk workload and many more.

**Comment by ishans-crest** [comment]
Hi @guilhemmarchand 
New repo has been created https://github.com/splunk-soar-connectors/trackme
CC: @junlinl-splunk @nastorSplunk

**Comment by guilhemmarchand** [comment]
Thank you very much @ishans-crest - I will look at the next steps then! much appreciated.
