### ISSUE TITLE
New SOAR App - [ManageEngine] ServiceDeskPlus

### ISSUE THREAD

**Issue by edro15** [splunk-soar-connectors/.github#120]
**Name of the app**
servicedeskplus

**Integration**
App integrates with [ManageEngine - Service Desk Plus](https://www.manageengine.com/products/service-desk/) on-prem.

**About**
![Supported actions](https://github.com/splunk-soar-connectors/.github/assets/25966020/df4746cc-1210-4598-8594-3158d58d8697)

**Comment by tonyc-phantom** [comment]
The repo https://github.com/splunk-soar-connectors/servicedeskplus has been created.
