### ISSUE TITLE
Commvault Cloud for Splunk SOAR

### ISSUE THREAD

**Issue by Cv-securityIQ** [splunk-soar-connectors/.github#121]
**Name of the app**
commvaultcloud

**Integration**
This app integrates with Commvault Platform Security APIs to retrieve information about threats.

**About**
Introducing the Commvault Cloud Splunk SOAR app. It enables security analysts to swiftly respond to threats using pre-built integrations, and playbooks for securing and auditing the Commvault Cloud platform.
 
With today's evolving threat landscape, data is under constant risk of data destruction and exfiltration. Organizations are challenged with responding to security events as quickly as they can to limit the impact of cyber threats on their production as well as backup data. This SOAR app allows organizations to monitor anomaly alerts from the Commvault Cloud platform, so they can respond with orchestrated actions to help fortify the data protection platform so they can recover in the event of a cyber incident.

Key features :
- Support for Commvault Cloud (software and SaaS)
- Suspicious file anomaly monitoring to indicate file encryption.
- Fetch Commvault Cloud file anomaly alerts over API
- Ability to export and view list of infected files for investigation

**Comment by tonyc-phantom** [comment]
Hello,

The repo https://github.com/splunk-soar-connectors/commvaultcloud has been created.
