### ISSUE TITLE
New SOAR App - ANY.RUN

### ISSUE THREAD

**Issue by anyrun-integrations** [splunk-soar-connectors/.github#124]
**Name of the app**
any.run

**Integration**
App integrates with [ANY.RUN](https://app.any.run) service.

**About**
Currently app is capable of:

- creating malware analysis tasks for files and urls;
- retrieving analysis reports and IOCs;
- retrieving threat intel for files, domains, urls, etc.

![Screenshot 2024-05-22 170053](https://github.com/splunk-soar-connectors/.github/assets/166487206/7c533ff4-e31d-4616-beef-68c81a8aad61)

**Comment by alexa-phantom** [comment]
Hello, thanks for reaching out. We have this repo already created in this project: https://github.com/splunk-soar-connectors/anyrun 
Would adding to this app work? Thanks

**Comment by anyrun-integrations** [comment]
Hello.

The existing anyrun app is developed by community and is not officially supported by ANY.RUN. While the app i propose is developed by ANY.RUN. We intend to collect our customers feedback and officially support and improve this app in a long run.

If i'm to create a PR to existing anyrun app it will replace around 90% of that projects code, which i do not believe to be the right this to do. Hence new app addition is proposed. We respect the community work and would like to provide our own solutions independently, without replacements. Thanks.

**Comment by alexa-phantom** [comment]
Hey @anyrun-integrations, you can find a fresh repo here: https://github.com/splunk-soar-connectors/any.run
Thanks!

**Comment by anyrun-integrations** [comment]
Hey @alexa-phantom .

Here's a [PR](https://github.com/splunk-soar-connectors/any.run/pull/1) for the new app. Unfortunately i'm not quite sure what to do about some failed tests yet. Kindly asking for some advice. Thanks in advance.
