### ISSUE TITLE
New SOAR App: Proofpoint ITM Splunk SOAR Connector

### ISSUE THREAD

**Issue by pdros-splunk** [splunk-soar-connectors/.github#126]
**Name of the app**
proofpoint-itm-splunk-soar-connector

**Integration**
Proofpoint ITM

**About**
Splunk SOAR Connector to interact with the Proofpoint ITM SaaS API. Proofpoint Insider Threat Management (ITM) is a people-centric SaaS solution that helps you protect sensitive data from insider threats and data loss at the endpoint. It combines context across content, behavior and threats to provide you with deep visibility into user activities. Proofpoint ITM helps security teams tackle the challenges of detecting and preventing insider threats. It can streamline their responses to insider-led incidents and provide insights that help prevent further damage.

**Comment by tonyc-phantom** [comment]
@pdros-splunk can we rename this connector to `proofpoint-itm` without the 'splunk-soar-connector'?

**Comment by pdros-splunk** [comment]
Hey @tonyc-phantom, ofc we can! Thank you.

**Comment by tonyc-phantom** [comment]
Thanks! https://github.com/splunk-soar-connectors/proofpoint-itm created.
