### ISSUE TITLE
New SOAR App: Google Chat App

### ISSUE THREAD

**Issue by pdros-splunk** [splunk-soar-connectors/.github#129]
**Name of the app**
google-chat-app

**Integration**
Google Chat

**About**
This app integrate services with Google Chat and manage Chat resources such as i.e messages.

**Comment by alexa-phantom** [comment]
Hey @pdros-splunk you are on a roll!!! Does `google-chat` work?

**Comment by pdros-splunk** [comment]
Hey @alexa-phantom, I try my best 😎. Yeah two clients of mine got it for tests without failure feedback 🤘

**Comment by tonyc-phantom** [comment]
Repo https://github.com/splunk-soar-connectors/google-chat has been created.
