### ISSUE TITLE
New SOAR App: Tile Mate device tracking connector.

### ISSUE THREAD

**Issue by unapped** [splunk-soar-connectors/.github#131]
**Name of the app**
life360-tile

**Integration**
Tile helps you keep track of things. Find misplaced things worldwide with Tile trackers. You can also locate your iPhone as well as headphones and other devices with builtin Tile technology supported by Intel. Modern laptops from Lenovo / Dell / HP and more support this technology. These laptops have builtin Tile technology supported by Intel and others. The technology allows for laptops to be located even when powered off.

**About**
Tile Mate SOAR App integrates with the Tile Mate API to allow you to find tile's and devices even when powered off.

**Comment by alexa-phantom** [comment]
Thanks @unapped! Let me know if there is anything more needed, otherwise feel free to close the request.
https://github.com/splunk-soar-connectors/life360-tile

**Comment by unapped** [comment]
Thankyou
