### ISSUE TITLE
Create private repo for `talosintelligencev2`

### ISSUE THREAD

**Issue by sodle-splunk** [splunk-soar-connectors/.github#134]
**Name of the app**
`talosintelligencev2`

**Integration**
Cisco Talos Intelligence

**About**
Cisco Talos is a Threat Intelligence platform. The connector will allow users with a valid Talos connector to query reputation information for URLs, domains, and IPs.

**_Please make this repo PRIVATE for now, as we are unsure if this app will be open source or not._**

**Comment by tonyc-phantom** [comment]
I have created the repo https://github.com/splunk-soar-connectors/talosintelligencev2 and set it's visibility to _private_.
