### ISSUE TITLE
New App: Checkphish.ai / Bolster.ai

### ISSUE THREAD

**Issue by dfederschmidt** [splunk-soar-connectors/.github#19]
**Name of the app**
checkphish

**Integration**
Integrates with https://checkphish.ai/ which is a variant of https://bolster.ai/

**About**
It provides two actions:
- detonate url
- check status

**Comment by rgil-splunk** [comment]
Repo has been created:  https://github.com/splunk-soar-connectors/checkphish

Please reopen and/or comment if there are any issues.
