### ISSUE TITLE
New App: LogRhythm NextGen SIEM

### ISSUE THREAD

**Issue by edro15** [splunk-soar-connectors/.github#22]
**LogRhythm NextGen SIEM**
logrhythmnextgensiem

**Integration**
LogRhythm (LR) is deprecating their SOAP web services in favour of a RESTful architecture.
This brand new app aims integrating LR NextGen SIEMs with Splunk SOAR leveraging RESTful API.

**About**

![LogRhythm_NextGen_SIEM](https://user-images.githubusercontent.com/25966020/141960944-0fdbcd90-c80f-4e08-8be1-0af4a88d6eb7.png)

**Comment by pzhou-splunk** [comment]
Hi Erica,

New repo's been created under https://github.com/splunk-soar-connectors/logrhythmnextgensiem
