### ISSUE TITLE
New App: Qintel QSentry

### ISSUE THREAD

**Issue by calvin-qintel** [splunk-soar-connectors/.github#23]
**Name of the app**
Qintel QSentry

**Integration**
Integrates with Qintel QSentry: https://www.qintel.com/products/qsentry/

**About**
Provides ip reputation lookups against QSentry data

**Comment by pzhou-splunk** [comment]
Hi Calvin,

The new repo has been created under https://github.com/splunk-soar-connectors/qintelqsentry

**Comment by calvin-qintel** [comment]
Hi @pzhou-splunk - what's the process for getting a PR reviewed and merged after it's submitted? I don't see anything that describes that in the contributing doc. We submitted a PR [here](https://github.com/splunk-soar-connectors/qintelqsentry/pull/1) and I wanted to make sure I wasn't missing a step to get it processed.

**Comment by pzhou-splunk** [comment]
Hi Calvin,

We've created a ticket from the label `PAPP-21521` tagged to your PR. It's in our backlog, and the team will get to it when we get a chance.
