### ISSUE TITLE
New App: Qintel QWatch

### ISSUE THREAD

**Issue by calvin-qintel** [splunk-soar-connectors/.github#24]
**Name of the app**
Qintel QWatch

**Integration**
Integrates with Qintel QWatch: https://www.qintel.com/products/qwatch/

**About**
With this app, users can fetch exposure alerts as events and discover exposed credentials associated with their organization. It provides two commands:

- search qwatch exposures: Queries QWatch for credential exposures by email or domain
- on poll: Generates events and artifacts from QWatch exposure alerts

**Comment by pzhou-splunk** [comment]
Hi Calvin,

The new repo has been created under https://github.com/splunk-soar-connectors/qintelqwatch
