### ISSUE TITLE
New App: Sophos Endpoint Protection

### ISSUE THREAD

**Issue by edro15** [splunk-soar-connectors/.github#25]
**Name of the app**
Sophos Endpoint Protection

**Integration**
The app aims integrating Sophos Endpoint Protection with Splunk SOAR leveraging the Endpoint API: https://developer.sophos.com/docs/endpoint-v1/1/overview

**About**
![image](https://user-images.githubusercontent.com/25966020/144450542-9859da18-8120-45bd-a34f-408adcf5da4b.png)

**Comment by rgil-splunk** [comment]
@edro15 repo has been created at https://github.com/splunk-soar-connectors/sophosendpointprotection
