### ISSUE TITLE
New App Repository: Fireeye Central Management

### ISSUE THREAD

**Issue by dfederschmidt** [splunk-soar-connectors/.github#26]
**Name of the app**
fireeyecentralmanagement

**Integration**
Fireeye Central Management

**About**

![Screenshot 2021-12-06 at 14 35 45](https://user-images.githubusercontent.com/2430239/144855415-7e847ce0-ef91-4bc5-8bbb-65ef39dab8fb.png)

**Comment by pzhou-splunk** [comment]
Hi Daniel,

New repo has been created under https://github.com/splunk-soar-connectors/fireeyecentralmanagement
