### ISSUE TITLE
New App: FireMon Security Manager

### ISSUE THREAD

**Issue by Trek333** [splunk-soar-connectors/.github#28]
**Name of the app**
firemonsecuritymanager

**Integration**
FireMon Security Manager

**About**
This App exposes various FireMon Security Manager API endpoints as actions.

Supported Actions
get domain - Get a domain by ID
get devicegroup - Get a DeviceGroup by ID
remove devicegroup - Remove a Device from a DeviceGroup
assign devicegroup - Assign a Device to a DeviceGroup
test connectivity - Validate the asset configuration for connectivity using supplied configuration

![image](https://user-images.githubusercontent.com/16667565/146242934-fad259e1-279b-4da3-be1b-68a27ab19ef4.png)

**Comment by rgil-splunk** [comment]
Repo created at https://github.com/splunk-soar-connectors/firemonsecuritymanager
