### ISSUE TITLE
New App: Lansweeper

### ISSUE THREAD

**Issue by crestdatasystems** [splunk-soar-connectors/.github#29]
**Name of the app**
lansweeper

**Integration**
Lansweeper

**About**
This app integrates with Lansweeper to perform investigative actions

Supported Actions:
test connectivity: Validate the asset configuration for connectivity using supplied configuration
list authorized sites: Retrieve authorized sites from Lansweeper with their ID(s) and names
hunt ip: Fetch the details of the asset from the Lansweeper platform for the given site ID and IP address
hunt mac: Fetch the details of the asset from the Lansweeper platform for the given site ID and MAC address

![image](https://user-images.githubusercontent.com/60967033/146755844-2af7bb16-1c28-48b0-b933-d85124876d69.png)

**Comment by rgil-splunk** [comment]
Repo created at https://github.com/splunk-soar-connectors/lansweeper
