### ISSUE TITLE
New App Request: TwinWave

### ISSUE THREAD

**Issue by twbryan** [splunk-soar-connectors/.github#32]
**Name of the app**
twinwave

**Integration**
The TwinWave analysis platform (https://www.twinwave.io)

**About**
The app allows analysis and playbook authors to integrate with the TwinWave platform, which is focused on investigating URLs and files for potential security threats, like phishing and malware.

**Comment by pzhou-splunk** [comment]
new repo created at https://github.com/splunk-soar-connectors/twinwave
