### ISSUE TITLE
New App: JupiterOne

### ISSUE THREAD

**Issue by achandya-crest** [splunk-soar-connectors/.github#34]
**Name of the app**
JupiterOne

**Integration**
JupiterOne

**About**
This app integrates with JupiterOne to perform investigative actions

Supported Actions:
test connectivity: Validate the asset configuration for connectivity using supplied configuration parameters
run query: Run a search query

<img width="933" alt="image" src="https://user-images.githubusercontent.com/70213464/156114687-2173120c-42e4-4352-a6da-8c1a82efe919.png">

Thank you for contributing to Splunk SOAR!

**Comment by crestdatasystems** [comment]
Thanks @achandya-crest for helping out with this repo creation request as we were facing some issues.

**Comment by pzhou-splunk** [comment]
repo created at https://github.com/splunk-soar-connectors/jupiterone
