### ISSUE TITLE
New app for SOAR Playbook Utils

### ISSUE THREAD

**Issue by phantom-bneises** [splunk-soar-connectors/.github#41]
**playbookutils**
The name of app your are contributing. Please ensure the app name
follows our [naming convention](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONVENTIONS.md).

**Integration**
Phantom Playbooks

**About**
Retrieves and builds a tree of a parent and child playbook runs and app runs. Helpful for debugging and visualizing more complicated playbook and app runs.

Thank you for contributing to Splunk SOAR!

**Comment by rgil-splunk** [comment]
Repo created at https://github.com/splunk-soar-connectors/playbookutils
