### ISSUE TITLE
New App: Tabular Report Generator

### ISSUE THREAD

**Issue by ricardom-splunk** [splunk-soar-connectors/.github#43]
**Name of the app**
Tabular Report Generator

**Integration**
None

**About**
The Tabular Report Generator (TRG) is a utility app for Splunk SOAR to generate tabular reports within playbooks to be delivered via the SMTP app.

**Comment by pzhou-splunk** [comment]
new repo created at https://github.com/splunk-soar-connectors/tabularreportgenerator
