### ISSUE TITLE
New repo for fuse box utility app

### ISSUE THREAD

**Issue by zamastyle** [splunk-soar-connectors/.github#49]
**Name of the app**
fuseboxutility

**Integration**
Splunk SOAR (Internal Utility App)

**About**
Fuse Box is an app to help deconflict incoming events from within playbook contexts

Thank you for contributing to Splunk SOAR!

**Comment by pzhou-splunk** [comment]
repo created at https://github.com/splunk-soar-connectors/fuseboxutility
