### ISSUE TITLE
New repo for illumio SOAR App

### ISSUE THREAD

**Issue by dsommerville-illumio** [splunk-soar-connectors/.github#54]
**Name of the app**
illumio

**Integration**
Integrates Splunk SOAR with the Illumio Core Policy Compute Engine.

**About**
The initial version of the app will provide SOAR users with the ability to block traffic on a given port and protocol throughout their network using Illumio policy configuration.

**Comment by rgil-splunk** [comment]
Repo created at https://github.com/splunk-soar-connectors/illumio
