### ISSUE TITLE
New App: Qintel PMI

### ISSUE THREAD

**Issue by calvin-qintel** [splunk-soar-connectors/.github#56]
**Name of the app**
Qintel PMI (qintelpmi)

**Integration**
Integrates with Qintel PMI: https://www.qintel.com/products/pmi/

**About**
Qintel’s Patch Management Intelligence (PMI) product simplifies the vulnerability management process by providing vital context around reported Common Vulnerabilities and Exposures. With this app, users can query PMI to surface CVEs that are known by Qintel to be leveraged by adversaries of all stripes.

**Comment by pzhou-splunk** [comment]
repo created at https://github.com/splunk-soar-connectors/qintelpmi
