### ISSUE TITLE
New App: Sandfly Security

### ISSUE THREAD

**Issue by gitsnapp** [splunk-soar-connectors/.github#58]
**Name of the app**
Sandfly Security (sandflysecurity)

**Integration**
Integrates with Sandfly Security - Agentless Linux Security (https://www.sandflysecurity.com/)

**About**
Integrates with the Sandfly Security Server to initiate a Sandfly scan of a specified system in order to track down intruders, malware, an other security breaches.

**Comment by rgil-splunk** [comment]
Repo created at: https://github.com/splunk-soar-connectors/sandflysecurity
