### ISSUE TITLE
New App: Azure DevOps

### ISSUE THREAD

**Issue by import-au** [splunk-soar-connectors/.github#60]
**Name of the app**
Azure DevOps

**Integration**
Azure DevOps

**About**
Azure DevOps Services for teams to share code, track work, and ship software. Azure Pipelines Continuously build, test, and deploy to any platform and cloud.

Thank you for contributing to Splunk SOAR!

**Comment by rgil-splunk** [comment]
Repo created at https://github.com/splunk-soar-connectors/azuredevops
