### ISSUE TITLE
Recorded Future Sandbox

### ISSUE THREAD

**Issue by christian-recordedfuture** [splunk-soar-connectors/.github#62]
** Name of App **
Recorded Future Sandbox

** Integration**
Integration with Recorded Future Sandbox

** About **
The Recorded Future Sandbox App allows for submission of URL and file samples to the Recorded Future Sandbox and retrieve submission result reports.

**Comment by rgil-splunk** [comment]
Repo created at https://github.com/splunk-soar-connectors/recordedfuturesandbox
