### ISSUE TITLE
Carbon Black Cloud App for Splunk SOAR

### ISSUE THREAD

**Issue by mrangelov-cb** [splunk-soar-connectors/.github#63]
**Name of the app**
carbonblackcloud

**Integration**
Carbon Black Cloud

**About**
The application provides means to ingest alerts from Carbon Black Cloud (via the REST API) and about 30 Carbon Black Cloud actions such as dismiss alert, get enriched events, set device policy, endpoints actions that utilize Live Response, watchlist and feeds manipulation.

**Comment by rgil-splunk** [comment]
Repo created at https://github.com/splunk-soar-connectors/carbonblackcloud
