### ISSUE TITLE
zabbix

### ISSUE THREAD

**Issue by ricardom-splunk** [splunk-soar-connectors/.github#64]
**Name of the app**
zabbix

**Integration**
Zabbix - https://www.zabbix.com/

**About**
This connector includes the following actions:
- test_connectivity
- get_host_info
  - Fetch a JSON with all the available (cached) information about a Zabbix agent/host
- execute_script
  - Execute an EXISTING Zabbix script, given the script name or script id

**Comment by rgil-splunk** [comment]
Repo created at https://github.com/splunk-soar-connectors/zabbix
