### ISSUE TITLE
New App: Varonis Data Security Platform app for Splunk SOAR

### ISSUE THREAD

**Issue by vkorenkov-varonis** [splunk-soar-connectors/.github#70]
**Name of the app**
varonisdsp

**Integration**
Varonis Data Security Platform app for Splunk SOAR

**About**
This pack enables you to streamline alerts and related forensic information from Varonis DSP.

What does this app do?
- Enables retrieving alerts and manage alert status.
- Enables retrieving information related to alerts for investigation and threat hunting.
![image](https://user-images.githubusercontent.com/99330808/215521408-aec9c457-f5c5-4d01-97d1-82dd43c18595.png)

**Comment by rgil-splunk** [comment]
Repo created at https://github.com/splunk-soar-connectors/varonisdsp
