### ISSUE TITLE
New app for Blackhawk Network, Inc. - https://splunk.atlassian.net/browse/FDSE-1589

### ISSUE THREAD

**Issue by patrykdros97** [splunk-soar-connectors/.github#71]
**App Name**
APP Name: File Share Manipulator
proposed repo name: filesharemanipulator

**Integration**
SMB, WMI (TCP445 and TCP135), NFS (TCP 111) protocols

**Description**
File share manipulator is an application that has the ability to manipulate files on a specific server. After two actions get_file and put_file, the user is able to add a specific file to a specific place, as well as download a desired file from the appropriate place.

**Comment by rgil-splunk** [comment]
Repo created at https://github.com/splunk-soar-connectors/filesharemanipulator
