### ISSUE TITLE
Trellix Malware Analysis

### ISSUE THREAD

**Issue by asur1on** [splunk-soar-connectors/.github#72]
trellixax
The name of app your are contributing. Please ensure the app name
follows our [naming convention](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONVENTIONS.md).

**Integration**
Trellix Malware Analysis 

**About**
This is an update to Fireeye AX. McAfee and FireEye merged into Trellix. Adding new action and updated existing actions

Thank you for contributing to Splunk SOAR!

**Comment by rgil-splunk** [comment]
Repo created at: https://github.com/splunk-soar-connectors/trellixax

cc: @nastorSplunk for awareness
