### ISSUE TITLE
New App: CrowdSec CTI App for Splunk SOAR

### ISSUE THREAD

**Issue by sbs2001** [splunk-soar-connectors/.github#73]
**Name of the app**

crowdsec

**Integration**
Integrates Splunk SOAR with CrowdSec's CTI API

**About**

Allows users to enrich IP addresses with intelligence from [CrowdSec CTI API](https://www.crowdsec.net/product/threat-intelligence)

**Comment by rgil-splunk** [comment]
Repo created at: https://github.com/splunk-soar-connectors/crowdsec
