### ISSUE TITLE
New app for Client sekoia.io by Patryk Dros(FDSE) 

### ISSUE THREAD

**Issue by pdrossplunk** [splunk-soar-connectors/.github#74]
Name of the app: sekoiaio

Integration: https://www.sekoia.io/

About: New SOAR App whose actions will be able to manipulate STIX bundles and represent an external system that can be queried to enrich observables.

**Comment by rgil-splunk** [comment]
Repo created at https://github.com/splunk-soar-connectors/sekoiaio
