### ISSUE TITLE
Yara Scanner

### ISSUE THREAD

**Issue by jrm16020** [splunk-soar-connectors/.github#78]
**Name of the app**
yara

**Integration**
Implements Yara scanning capabilities using remotely sourced/maintained rules files

**About**
The app can be used for scanning with Yara to accomplish tasks like malware analysis, secrets scanning, etc.

Thank you for contributing to Splunk SOAR!

**Comment by mpan-splunk** [comment]
repo created at: https://github.com/splunk-soar-connectors/yara
