### ISSUE TITLE
Requesting new app repo for BigID Data Discovery

### ISSUE THREAD

**Issue by dcoleman2** [splunk-soar-connectors/.github#81]
**Name of the app**
bigiddatadiscovery

**Integration**
[BigID Data Intelligence Platform](https://bigid.com/data-intelligence-platform/)

**About**
BigID is a next-gen data discovery and intelligence platform for the data you know and the data you don’t know. The BigID Data Discovery App for Splunk SOAR provides functionality allowing business users to take action on their data, regardless of the type or location. With actions for searching BigID's data catalog, retrieving PII findings, executing a scan for given data sources and retrieving those scan results, as well as retrieving BigID audit logs, business users will have an invaluable tool for building robust playbooks to action and protect sensitive data.

**Comment by mpan-splunk** [comment]
New repo is created at: https://github.com/splunk-soar-connectors/bigiddatadiscovery
