### ISSUE TITLE
ClearPass Policy Manager

### ISSUE THREAD

**Issue by dfederschmidt** [splunk-soar-connectors/.github#82]
**Name of the app**
clearpasspolicymanager

**Integration**
[The technology that your app integrates with.
](https://www.arubanetworks.com/techdocs/ClearPass/6.7/PolicyManager/Content/CPPM_UserGuide/About%20ClearPass/About_ClearPass.htm#:~:text=In%20ClearPassPolicy%20Manager%2C%20a,of%20users%20on%20a%20switch.)

**About**
The app will provide a set of actions for integrating with ClearPass Policy Manager

**Comment by rgil-splunk** [comment]
Repo created at: https://github.com/splunk-soar-connectors/clearpasspolicymanager
