### ISSUE TITLE
New App: ReversingLabs TitaniumScale

### ISSUE THREAD

**Issue by ivukovicRL** [splunk-soar-connectors/.github#85]
**Name of the app**
reversinglabstitaniumscale

**Integration**
ReversingLabsTitaniumScale

**About**
App utilizes ReversingLabs TitaniumScale APIs:

1. upload sample
2. get report

We already have a similar app: https://github.com/splunk-soar-connectors/reversinglabs-tiscale

After publishing this app we will probably remove the old one. We intentionally didn't upgrade the existing app because this is a cleaner approach and the review process will be much easier this way.

This app has much different implementation approach (utilizes our own helper lib https://pypi.org/project/reversinglabs-sdk-py3/).

**Comment by mpan-splunk** [comment]
New repo is created at: https://github.com/splunk-soar-connectors/reversinglabstitaniumscale
