### ISSUE TITLE
New App: Microsoft Intune

### ISSUE THREAD

**Issue by nikhileshcr-splunk** [splunk-soar-connectors/.github#88]
**Name of the app**
microsoftintune

**Integration**
Microsoft Intune

**About**
Connects to Microsoft Intune using MS Graph REST API services to support managed device actions.

**Supported Actions**

- list managed devices - List properties and relationships of the managedDevice objects.
- test connectivity - Validate the asset configuration for connectivity using the supplied configuration

**Comment by mpan-splunk** [comment]
https://github.com/splunk-soar-connectors/microsoftintune
