### ISSUE TITLE
New App: Shodan 

### ISSUE THREAD

**Issue by nikhileshcr-splunk** [splunk-soar-connectors/.github#89]
**Name of the app**
shodanapi

**Integration**
Shodan - https://developer.shodan.io/api

**About**

This app integrates with the Shodan Search engine. It supports search and on-demand scanning APIs.

**Supported Actions** 

- shodan scan individual - Get the status of a scan request
- scan status bulk - Get list of all the created scans
- scan internet - Crawl the Internet for a specific port and protocol using Shodan
- scan ip with services - A pipe-separated list of IPs or netblocks (in CIDR notation) that should get crawled with services.
- scan ip only - Request Shodan to crawl an IP/ netblock
- scan protocols - List all protocols that can be used when performing on-demand Internet scans via Shodan.
- scan ports - List all ports that Shodan is crawling on the Internet.
- search token - Break the search query into tokens
- search parameter - List all search facets, filters
- search shodan - Search Shodan using the same query syntax as the website and use facets to get summary information for different properties.
- host count - Search Shodan without Results
- search ip - Returns all services that have been found on the given host IP.
- test connectivity - Validate the asset configuration for connectivity using supplied configuration

**Comment by mpan-splunk** [comment]
Hi @nikhileshcr-splunk , we already have a repo named shodan: https://github.com/splunk-soar-connectors/shodan , please use a different repo name.

**Comment by nikhileshcr-splunk** [comment]
Hi @mpan-splunk, can you please create a repo with the name **shodanapi**?

Thanks.

**Comment by mpan-splunk** [comment]
Here it is @nikhileshcr-splunk : https://github.com/splunk-soar-connectors/shodanapi
