### ISSUE TITLE
New App: OPSWAT Filescan

### ISSUE THREAD

**Issue by anikobartos** [splunk-soar-connectors/.github#90]
**Name of the app**
opswatfilescan

**Integration**
[OPSWAT Filescan](https://www.opswat.com/products/filescan)
Documentation: https://docs.opswat.com/filescan

**About**
This app includes the OPSWAT Filescan basic integration that does the following:

- **detonate url**: Retrieve detonation analysis results for URL
- **detonate file**: Retrieve detonation analysis results for file
- **search**: Search for scan reports on Filescan using parameters specified in the 'query' field
- **file reputation**: Get the reputation for one given hash (returns with the last 10 Filescan reports)
- **ioc reputation**: Get the reputation for one given IOC (returns with the last 10 Filescan reports)

**Comment by mpan-splunk** [comment]
App repo has been created: https://github.com/splunk-soar-connectors/opswatfilescan
