### ISSUE TITLE
Please create a new app repository

### ISSUE THREAD

**Issue by bentleymi** [splunk-soar-connectors/.github#91]
**Name of the app**
OpenAI API ChatGPT for SOAR (openaiapichatgpt)

**Integration**
Integrates SOAR w/OpenAI API & ChatGPT

**About**
Integrates SOAR w/OpenAI API & ChatGPT

Thanks in advance!

**Comment by mpan-splunk** [comment]
Repo is created at: https://github.com/splunk-soar-connectors/openaiapichatgpt
