### ISSUE TITLE
Intezer Labs Integration App

### ISSUE THREAD

**Issue by guysl10** [splunk-soar-connectors/.github#92]
**Name of the app**
The name of app your are contributing. Please ensure the app name
follows our [naming convention](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONVENTIONS.md).

> **Name of the app - Intezer**

**Integration**
The technology that your app integrates with.

> **Programming language - Python.
> Using the library  - [Intezer-SDK](https://pypi.org/project/intezer-sdk/)**

**About**
Description of what the app does.

> **Intezer connector for Splunk SOAR enables security teams to automate the analysis, detection, and response of threats by integrating Intezer's technology into their Splunk workflows.**

Thank you for contributing to Splunk SOAR!

**Comment by mpan-splunk** [comment]
Hi @guysl10 , we already have app name with 'intezer'. Could you please provide a different name? Thxs! (Ex. intezerlabs)

**Comment by guysl10** [comment]
Hey,
Are you sure? I think it's a misunderstanding.
Are you sure there is already a connector named Intezer? I tried to find
and did not found.

Thanks,
Guy Salomon

**Comment by mpan-splunk** [comment]
Hi @guysl10 , here it is: https://github.com/splunk-soar-connectors/intezer, it's existed. Please let me know a new name. Thxs!

**Comment by guysl10** [comment]
Hey @mpan-splunk, I get a 404 error for entering this [URL](https://github.com/splunk-soar-connectors/intezer).
Maybe it's an inactive repo? Can we replace this repo with the new one?

**Comment by mpan-splunk** [comment]
Hi @guysl10 , it's private internal app and not released yet. I'll check in further.

**Comment by royhalevi** [comment]
Thank you @mpan-splunk for the clarification.
I understand that an internal app currently occupies the name 'Intezer'. This seems to be an older application developed for Phantom, which is now possibly private and may no longer be in use.

To free up the official name for the new app, could we consider renaming the old application to mark it as deprecated?
This would allow us to proceed with the 'Intezer' name for this new, relevant project.

**Comment by mpan-splunk** [comment]
Hi @royhalevi @guysl10 , you could develop code at https://github.com/splunk-soar-connectors/intezerlabs
Thxs for contributing!
