### ISSUE TITLE
New App: Google Sheets

### ISSUE THREAD

**Issue by nikhileshcr-splunk** [splunk-soar-connectors/.github#93]
**Name of the app**
googlesheets

**Integration**
Google Sheets API

**About**
This app allows various file manipulation actions to be performed on Google Sheets

### Supported Actions 

**create_spreadsheet** - create a new spreadsheet and share it with users 
**add_new_rows** - Use this action to add new rows to the sheet 
**test connectivity** - Validate the asset configuration for connectivity using the supplied configuration

**Comment by mpan-splunk** [comment]
Repo is created at: https://github.com/splunk-soar-connectors/googlesheets
Thanks for contributing!
