### ISSUE TITLE
nistnvd

### ISSUE THREAD

**Issue by trishapancho** [splunk-soar-connectors/.github#97]
**Name of the app**
nistnvd

**Integration**
NIST NVD API

**About**
App to query the National Vulnerability Database (NVD) which is a database, maintained by National Institute of Standards and Technology (NIST) for Common Vulnerabilities and Exposures (CVE) informaton.

Thank you for contributing to Splunk SOAR!

**Comment by mpan-splunk** [comment]
Repo has been created at: https://github.com/splunk-soar-connectors/nistnvd
