### ISSUE TITLE
Cydarm

### ISSUE THREAD

**Issue by bliew-splunk** [splunk-soar-connectors/.github#98]
**Name of the app**
The name of app your are contributing. Please ensure the app name
follows our [naming convention](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONVENTIONS.md).
cydarm

**Integration**
The technology that your app integrates with.
Cydarm: https://www.cydarm.com/about

**About**
Description of what the app does.
Exposes a subset of the Cydarm API as SOAR actions.
For example, the ability to create a Cydarm case.

Thank you for contributing to Splunk SOAR!

**Comment by mpan-splunk** [comment]
New repo is created at: https://github.com/splunk-soar-connectors/cydarm
