### ISSUE TITLE
vectraxdr

### ISSUE THREAD

**Issue by crestdatasystems** [splunk-soar-connectors/.github#99]
**Name of the app**
vectraxdr

**Integration**
splunksoar

**About**
Using Splunk SOAR, the Vectra XDR App enables the security operations team to consume the industry's richest threat signals spanning public cloud, SaaS, identity and data center networks and take appropriate action whether automated, semi-automated, or manual

Thank you for contributing to Splunk SOAR!

**Comment by mpan-splunk** [comment]
Repo is created at: https://github.com/splunk-soar-connectors/vectraxdr
